version: '3.2'

services:
    db:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
    server:
        build:
          context: ./
        env_file:
            - .env
        volumes:
            - ./:/code
        ports:
            - '9000:9000'
        depends_on:
            - db

volumes:
  postgres-data:
