# Generated by Django 3.0.5 on 2020-11-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201112_1149'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
