# Generated by Django 3.0.5 on 2020-10-05 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('display_picture', models.FileField(blank=True, default=None, null=True, upload_to='user-profile/')),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=32)),
                ('join_date', models.DateField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('signature', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
