# Generated by Django 3.0.5 on 2020-10-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201007_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='middle_name',
        ),
    ]
