# Generated by Django 3.0.5 on 2020-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_group',
            field=models.ManyToManyField(blank=True, to='usergroup.UserGroup'),
        ),
    ]
